### ISSUE TITLE
No easy way to go back from Changes browser

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#1247] opened 2016-10-04 14:33 UTC
If you browse through tens of changes pages and then want to go back, there is no way. Project / Branch / Language navigation bar is missing.

### Steps to reproduce
1. Go to https://l10n.opensuse.org/changes/?page=2&lang=cs&project=yast-registration&subproject=master
2. Attempt to go back to https://l10n.opensuse.org/projects/yast-registration/master/cs/ without editing URL

### Actual behaviour
No way to go back except attempt to use browser Back feature.

### Expected behaviour
One-click go back

### Server configuration
Weblate 2.6
Python 2.7.9
Django 1.8.4
six 1.9.0
python-social-auth 0.2.7
Translate Toolkit 1.14.0-rc1
Whoosh 2.7.0
Git 1.8.5.6
Pillow (PIL) 1.1.7
dateutil 2.4.2
lxml 3.2.3
django-crispy-forms 1.5.2
compressor 1.5
djangorestframework 3.3.3
pytz 2013.9
pyuca N/A
Database backends: django.db.backends.mysql

**Comment by nijel** [comment] 2016-10-04 15:10
Duplicate of #1184.

**Closed by nijel** 2016-10-04 15:10 UTC
