### ISSUE TITLE
Popup in every change on Chrome

### ISSUE THREAD

**Issue by elchevive** [nijel/weblate#1254] opened 2016-10-14 12:53 UTC
For every string I translate on l10n.opensuse.org I got this popup in Chrome:

![image](https://cloud.githubusercontent.com/assets/1202332/19387637/dfae5a10-91f1-11e6-9d5d-e711f5b8bbb4.png)

Its very annoying.

**Comment by harikv** [comment] 2016-10-15 06:34
I would like to take this on

**Comment by nijel** [comment] 2016-10-15 07:24
The problem is probably here: https://github.com/nijel/weblate/blob/master/weblate/static/loader-bootstrap.js#L905 It should not fire in case user did the action...

**Comment by nijel** [comment] 2016-10-21 13:30
@harikv any progress on this?

**Comment by harikv** [comment] 2016-10-21 13:32
Should have the pull request ready by tomorrow. Had to travel today.

**Comment by nijel** [comment] 2016-10-21 13:33
No problem, I just wanted to check if you're still looking at this :-).

**Comment by harikv** [comment] 2016-10-22 16:08
Hey these are my findings on the bug. It is not reproducible in localhost because, the beforeunload is listened to only in Zen mode. However, on the l10.opensuse.org page, there is a new chunk of code added. 
`if ($('.translation-editor').length > 0) {
        var origContent = $('.translation-editor').val();
        $window.on('beforeunload', function() {
            if ($('.translation-editor').val() != origContent) {
                return gettext('There are some unsaved changes, are you sure you want to leave?');
            }
        });
    }`
This is triggered even when the form's submit button is pressed, because that is not ajaxified and involves a page change essentially. I'm not sure how to go about fixing this except to ajaxify the form POST request. Even then the l10.opensuse.org website has to be updated.

**Comment by nijel** [comment] 2016-10-23 15:36
Thanks for looking into this! It seems that this change is coming from https://github.com/matejcik/weblate/commit/3b36a45b936528ccdb96ae069f3d31be9840d7d6 which is not upstream and used only on the openSUSE Weblate.

Closing this is issue as code causing this is not present in our repo.

**Closed by nijel** 2016-10-23 15:36 UTC
Labels: bug, hacktoberfest, newbie
