### ISSUE TITLE
Suggestion for Search

### ISSUE THREAD

**Issue by lem9** [nijel/weblate#879] opened 2015-10-16 13:38 UTC
When I do a search, I always have to change the search type to substring, so I suggest that this be the default instead of fulltext.

**Comment by nijel** [comment] 2015-10-18 18:04
Is just because fulltext doesn't always work as expected? The problem is that substring search is quite expensive on the database side so I'd really want to avoid it, however with current fulltext implementation it's sometimes not possible to find some strings. But that should be changed at some point, see #800.

**Comment by lem9** [comment] 2015-10-18 23:51
Well in all of my attempts it never found the one word I was trying. I got quick responses that the string was not found.

**Comment by nijel** [comment] 2015-10-19 06:43
Okay, I really need to find time to look into other fulltext search options. Closing this in favor of #800.

**Closed by nijel** 2015-10-19 06:43 UTC
Labels: question
