### ISSUE TITLE
Wrong translations shown after import

### ISSUE THREAD

**Issue by rvanlaak** [nijel/weblate#939] opened 2015-11-24 15:03 UTC
#830 solved the XLIFF compatibility, we were able to succesfully import our project using the following command. Our source files makes use of translation keys as the source (like: `page_name.text`), and every language has it's own file, including the English main one:

```bash
./manage.py import_project myproject git@bitbucket.org:myproject/myproject.git xliff-branch \
   --base-file-template=app/Resources/translations/%s.en.xliff \
   --file-format=xliff \
   app/Resources/translations/**.*.xliff
```
Unfortunately some unexpected behaviour appeared afterwards, as can be explained based on the following screenshot:

![knipsel](https://cloud.githubusercontent.com/assets/2707563/11370498/59b8eb32-92c4-11e5-9a1e-3ea5aacb369a.PNG)

1. The `source` string is the English string, but should be the translation key
2. The English translation that is shown on top of the source does not match the `source`.
3. We're translating for German, but the translation does not come close to the `source`.

So, where did this go wrong? The translations should be linked to eachother based on the source `translation keys` right?

**Comment by nijel** [comment] 2015-11-24 15:09
Indeed they should be. Did you do the fresh import? Also is there context shown for the string and does it match the english key?

**Comment by rvanlaak** [comment] 2015-11-24 15:31
Yes, removed the entire project and did a fresh import, which took around 30 minutes to complete.

The context seems to be the translation id, right aligned at the source field as a text label. If the source edit pencil is clicked, the context id is shown as a non-editable field. Can this context be related to an id in the database, or what does that id do?

Another thing that would be nice for monolingual components, is that all other languages also can be edited from the same page directly, as they are already shown :+1:

**Comment by nijel** [comment] 2015-11-24 15:41
I can't reproduce it here with XLIFF files in our testsuite: https://github.com/nijel/weblate-test/tree/master/xliff-mono . Can you please send me xliff files to reproduce it? Just one translation + English is enough.

**Comment by nijel** [comment] 2015-11-24 16:05
I've made some adjustments, but I'm not sure they will fix your problem...

**Comment by rvanlaak** [comment] 2015-11-24 16:22
Did pull the latest changes, but now it seems that the other translations that are shown don't match the component.

![image](https://cloud.githubusercontent.com/assets/2707563/11372843/da24a2f6-92cf-11e5-94b7-60c4c41d48e1.png)

The Dutch / German translations from this screenshot are actually shown in every module we try to translate.

**Comment by nijel** [comment] 2015-11-24 17:16
Well these are shown because you've enabled them in secondary languages: https://docs.weblate.org/en/latest/user/profile.html#secondary-languages

**Comment by nijel** [comment] 2015-11-24 18:18
BTW: Can you share some of the files with me? I'd like to see why the strings are so mixed up...

**Comment by nijel** [comment] 2015-11-25 12:42
Should be fixed now...

**Comment by rvanlaak** [comment] 2015-11-25 12:47
:+1: based on the commit I think no new import is needed?

**Comment by nijel** [comment] 2015-11-25 12:57
It is needed to reimport it. You don't have to create the projects again, ``./manage.py loadpo --force myproject`` should do the trick.

**Comment by rvanlaak** [comment] 2016-03-09 14:25
@nijel We tried to import the .xliff files again today, but somehow the `trans-unit id` vs. `source` matching still seems to go wrong while importing:

![xliff-weblate](https://cloud.githubusercontent.com/assets/2707563/13638006/81b042ae-e60a-11e5-88c5-f514189cf896.PNG)

The xliff files look like this for EN, NL and DE:

![xliff-de](https://cloud.githubusercontent.com/assets/2707563/13638022/9d236c64-e60a-11e5-93f9-6230bb819a7c.PNG)
![xliff-en](https://cloud.githubusercontent.com/assets/2707563/13638021/9d232236-e60a-11e5-88ae-81aa68f70f22.PNG)
![xliff-nl](https://cloud.githubusercontent.com/assets/2707563/13638023/9d24e56c-e60a-11e5-9625-cc2c8f85bdc7.PNG)

So there could be two things that are going wrong:
* During the import, the "source" is not matched between languages. 
* During the import, the order of the `trans-unit` elements is used between all languages to match the items.

Does weblate use the trans-unit id, the source, or the order of the items during the import?

**Comment by TomSchillemans** [comment] 2016-03-16 12:04
How does Weblate use this `id` attribute?
Also should we have the English translation string as `source` and if so. How does Weblate handle English translation string changes?

Also according to the specifications, you should use `resname` to identify the resource.

> Identifier - The id attribute is used in many elements as a reference to the original corresponding code data or format for the given element. The value of the id element is determined by the tool creating the XLIFF document. It may or may not be a resource identifier. The identifier of a resource should, at least, be stored in the resname attribute.

http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#id

**Comment by nijel** [comment] 2016-03-17 14:34
The problem with XLIFF is that it's used in many variations, where many of these do not match the specification. This issue being nice example - it's about storing identifiers in the \<source> tag, while according to specification:

> The content of the \<source> is generally the translatable text

Weblate (or rather translate-toolkit) doesn't use resname at all. Actually I've not yet met XLIFF with ``resname`` different from ``id``, which is being used.

**Closed** 2016-03-17 14:37 UTC
Labels: bug

**Comment by nijel** [comment] 2016-03-17 14:39
@rvanlaak Your case should be now (really) fixed.

**Comment by rvanlaak** [comment] 2016-03-17 14:39
The way our `.xlf` should look actually it the think I'd like to agree on. It is quite easy for us to change the export script, as long as we know what Weblate (or translation-toolkit) expects.

Right now the `id` does not match the `source` between languages, the `source` is our translation key and originally is extracted from our nested `.yml` files.

So maybe you can provide guidelines on the structure of our monolingual `xliff` files? Hope we can provide clear instructions :+1:

**Comment by rvanlaak** [comment] 2016-03-17 14:41
@nijel awesome thanks for the commit! :rocket: 

We will let you know whether the import succeeded this time :+1:

**Comment by rvanlaak** [comment] 2016-03-23 11:09
@nijel everything is working as expected now, the import was successful.

See #1040 for another remark about the import.
