### ISSUE TITLE
Translation status bug

### ISSUE THREAD

**Issue by WTBenjamin** [nijel/weblate#668] opened 2015-03-05 13:51 UTC
The progress bar in translation status overview looks weird:
![Statistics bug](http://i.imgur.com/7LuVdEx.png)

As you can see there is one "fuzzy string" and one "string with failing checks". Shouldn't this result in a progress bar with green, yellow and red parts?
Hovering over the yellow part of the bar shows "fuzzy translation" instead of "translations with failing checks"

Am I misinterpreting the statistics, or is it just wrong?

**Comment by nijel** [comment] 2015-03-05 13:56
That looks indeed wrong. Can you please paste here the HTML code for the progress bar as well?

**Comment by WTBenjamin** [comment] 2015-03-05 14:00
No problem, here you go:
```
<td class="progress-cell">

<div class="progress">
  
  <div title="Good translations" style="width: 66.700000%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="66.700000" role="progressbar" class="progress-bar progress-bar-success"></div>
  
  
  <div title="Fuzzy translations" style="width: 33.300000%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="33.300000" role="progressbar" class="progress-bar progress-bar-warning progress-checks"></div>
  
  
  <div title="Translations with failing checks" style="width: 33.300000%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="33.300000" role="progressbar" class="progress-bar progress-bar-danger"></div>
  
</div>
</td>
```

**Comment by nijel** [comment] 2015-03-05 14:11
Hmm that adds up to 133%, that's why it's wrongly displayed :-).

**Comment by WTBenjamin** [comment] 2015-03-05 14:22
Yes and the titles and style classes are mixed up:
`title="Fuzzy translations"` occurs with `class="progress-bar progress-bar-warning progress-checks"`
and
`title="Translations with failing checks"` occurs with `class="progress-bar progress-bar-danger"`

**Comment by nijel** [comment] 2015-03-05 14:27
I've already fixed titles in 45c41ab :-).

Also I think I've found the root cause here - in case you're using monolingual format, the fuzzy strings are marked as being translated, what confuses rest of the code. I've fixed this, but the flag is already stored per unit, to update it, you need to run ```./manage.py fixup_flags --all```.

**Closed by nijel** 2015-03-05 14:27 UTC
Labels: bug

**Comment by WTBenjamin** [comment] 2015-03-05 14:40
Thank you very much!
I've never seen an open source project that is that well maintained and taken care of!!!

Suggestion:
Shouldn't the command be integrated in https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-2-to-2-3?

**Comment by nijel** [comment] 2015-03-05 14:52
It really makes sense only if someone was hit by this bug, so I'd not
recommend it generally (as it takes quite long on bigger instances).
