### ISSUE TITLE
When importing qt linguis files, source and target strings are changed

### ISSUE THREAD

**Issue by alexei38** [nijel/weblate#462] opened 2014-03-20 07:16 UTC
I generate ts files using lupdate
```
root@wheez64:/vagrant/weblate# lupdate path_to_project/projectname.pro
```
Receive ts file
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en">
<context>
    <name>AboutPage</name>
    <message>
        <source>&lt;b&gt;&lt;font size=&quot;+4&quot;&gt;ProjectName&lt;/font&gt;&lt;/b&gt;</source>
        <translation>&lt;b&gt;&lt;font size=&quot;+4&quot;&gt;ProjectName&lt;/font&gt;&lt;/b&gt;</translation>
    </message>
<context>
</TS>
```

I create subproject
```
./manage.py shell
from weblate.trans.models import SubProject, Project
SubProject.objects.create(
    name="ProjectName",
    slug="projectname",
    project=Project.objects.get(slug='projectname'),
    repo="/opt/git/ProjectName.git",
    push="/opt/git/ProjectName.git",
    branch="master",
    file_format="ts",
    template="",
    filemask="ProjectName/res/translations/*.ts"
)
```

I run psql console and search new unit
```
select * from trans_unit;
-[ RECORD 1 ]-----+-----------------------------------------------
id                | 1
translation_id    | 1
checksum          | 2ce53efab681fcae663f724af37e4568
location          | 
context           | AboutPage
comment           | 
flags             | 
source            | <b><font size="+4">NauSoftPhone</font></b>
target            | <b><font size="+4">Naumen SoftPhone</font></b>
fuzzy             | f
translated        | t
position          | 1
previous_source   | 
has_suggestion    | f
has_comment       | f
has_failing_check | f
num_words         | 2
contentsum        | 2ce53efab681fcae663f724af37e4568

```

When importing transformed html characters

This occurs as a function 
```
translate.storage.ts2.tsunit ->  _getsourcenode and _gettargetnode
```

How can I fix this behavior is that the original data is not changed when importing and exporting?

**Comment by stormi** [comment] 2015-07-17 13:30
I can confirm that, I imported a .ts file, made some changes, exported it again : all HTML entities have been converted to characters.

**Comment by stormi** [comment] 2015-07-21 14:42
So, after hours of digging, here is what I think: it's OK that in the database &apos; and &quot; are decoded (as are &gt;, &lt;, etc.) in source and translations.

However, in order to match Qt's tools behaviour and not cause unnecessary changes, &apos; and &quot; must be added back when the file is written to disk.

Here is an ugly patch to translate-toolkit that does the work for me. I'm not contributing it upstream because they'll laugh at me, but in case it helps someone, here it is.

```diff
diff --git a/translate/storage/ts2.py b/translate/storage/ts2.py
index 32ac899..fa8c5fc 100644
--- a/translate/storage/ts2.py
+++ b/translate/storage/ts2.py
@@ -487,5 +487,19 @@ class tsfile(lisa.LISAfile):
         # This will prevent self-closing tags in pretty_print mode
         for e in root.xpath("//*[not(./node()) and not(text())]"):
             e.text = ""
-        return etree.tostring(root, doctype=doctype, pretty_print=True,
-                              xml_declaration=True, encoding='utf-8')
+        import re
+        s1 = etree.tostring(root, doctype=doctype, pretty_print=True,
+                            xml_declaration=True, encoding='utf-8')
+
+        while True:
+            s2 = re.sub(r"(>[^<]*)'([^<]*<)",
+                        r'\1&apos;\2',
+                        s1)
+            s2 = re.sub(r'(>[^<]*)"([^<]*<)',
+                        r'\1&quot;\2',
+                        s2)
+            if s2 == s1:
+                return s1.replace("<?xml version='1.0' encoding='utf-8'?>",
+                                  "<?xml version=\"1.0\" encoding=\"utf-8\"?>")
+            else:
+                s1 = s2

```

**Comment by nijel** [comment] 2015-08-06 07:46
I think this is better to discuss at https://github.com/translate/translate, I don't really have good knowledge of ts files...

**Comment by nijel** [comment] 2016-07-24 10:16
Closing in favor of #1118 and https://github.com/translate/translate/pull/3465.

**Closed by nijel** 2016-07-24 10:16 UTC
Labels: bug, translate-toolkit
