### ISSUE TITLE
File content merge failed

### ISSUE THREAD

**Issue by martinpucik** [nijel/weblate#1080] opened 2016-04-19 12:22 UTC
Hi, 

uploading translated XLIFF for existing language ends with this error:

`File content merge failed: get() returned more than one Unit`

Currently I don't have access to logs from Weblate. 

Is there fix for this? 

Thanks

**Comment by nijel** [comment] 2016-04-19 12:41
This really sounds as a bug. What Weblate version is that?

**Comment by martinpucik** [comment] 2016-04-19 12:43
So far I can tell is Weblate-2.6. I'll try to get to the server soon.

**Comment by martinpucik** [comment] 2016-04-19 13:26
Ok, I got setup output: 

```
 * Weblate weblate-2.5-58-gfeef730
 * Python 2.7.5
 * Django 1.9.1
 * six 1.10.0
 * python-social-auth 0.2.13
 * Translate Toolkit 1.11.0
 * Whoosh 2.7.2
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.2.1
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * pyuca N/A
 * Database backends: django.db.backends.mysql
```

**Comment by martinpucik** [comment] 2016-04-20 13:01
And in the logs is only:

`ERROR Handled exception MultipleObjectsReturned: get() returned more than one Unit -- it returned 2!`

**Comment by nijel** [comment] 2016-04-20 13:45
That matches what I've expected. Can you try reimporting the translations? That should at least give better hint what causes the problem:

```sh
./manage.py loadpo --force --all
```

(Or you just problematic project/component instead of --all)

**Comment by GrotzkyD** [comment] 2016-04-24 10:34
I get the same error on uploading an iOS string resource - related?
Weblate version 2.5.0

What else do you need from me to check this?

**Comment by nijel** [comment] 2016-05-20 15:24
@GrotzkyD The above comment applies to you as well. This is most likely caused by wrong import or duplicate strings in the source. Both will be detected by current Weblate versions, but older versions could have missed that and generate duplicate units.

Anyway this will not happen since 8944bc8dd7db50e73f94349dd13e44022c6b0f1a, so I'm closing this issue as it's fixed in git.

**Closed by nijel** 2016-05-20 15:24 UTC
Labels: bug
