### ISSUE TITLE
Missing words in half sub projects after Pull changes from the remote repository

### ISSUE THREAD

**Issue by collex100** [nijel/weblate#1164] opened 2016-07-02 10:31 UTC
### Steps to reproduce
1. Pull changes from the remote repository
2.
3.

### Actual behaviour
Tell us what happens instead
![screenshot_1](https://cloud.githubusercontent.com/assets/11208423/16539873/56417cdc-4069-11e6-99af-2e30e44b0261.jpg)
Not displaying the word. But they are there, and even downloaded.
Missing words in half sub projects

### Expected behaviour
Tell us what should happen

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
 * Weblate weblate-2.5
 * Python 2.7.3
 * Django 1.8.5
 * six 1.10.0
 * python-social-auth 0.2.13
 * Translate Toolkit 1.13.0
 * Whoosh 2.7.0
 * Git 1.7.10.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.5.2
 * compressor 1.5
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.5.2
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment] 2016-07-19 10:57
Duplicate of #1165.

**Closed by nijel** 2016-07-19 10:57 UTC
Labels: question
